### ISSUE TITLE
[Feature]: implement Multistore functionality

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront-community/vendure#115]
### How the project can be improved?

Similarly to Magento, I have decided to not include the Multistore in the 1.0.0 version but in 1.1.0.

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rhclayto** [comment]
Does this mean using Vendure's Channels to create a multi-vendor store? I am looking forward to this feature if so!

**Comment by Baroshem** [comment]
@rhclayto 

To my knowledge yes. Would you be interested in developing that? :)

@michaelbromley could you please confirm and maybe add some useful info here about how it can be implemented?

**Comment by michaelbromley** [comment]
Hi all,

Yes, multi-store is implemented in Vendure with Channels. There are some docs about it here: https://www.vendure.io/docs/developer-guide/multi-tenant/

For the storefront, the main thing that needs to be done is to attach a `vendure-token` header or query string to all requests which is used to specify which Channel to use: https://www.vendure.io/docs/developer-guide/multi-tenant/#the-storefront

Once that is set, you should just be able to use all the exact same queries & mutations, and Vendure will return the inventory etc only for the current Channel.

**Comment by rhclayto** [comment]
> @rhclayto
> 
> To my knowledge yes. Would you be interested in developing that? :)
> 
> @michaelbromley could you please confirm and maybe add some useful info here about how it can be implemented?

I will start looking into the code structure & see if I can put a PR together.

**Comment by rhclayto** [comment]
Would you prefer using a header or a query string?

**Comment by Baroshem** [comment]
I would go for a header then. Lets keep it simple and close to Vendure approach :)

**Comment by michaelbromley** [comment]
You can technically use either. My opinion is that headers are cleaner.

**Comment by rhclayto** [comment]
Was this feature actually implemented? I only see changes to the documentation (a general paragraph about Multistore).

Just a note: I got something partially working, but it was ugly. All the abstraction in this code made my head hurt! My programming chops, not up to snuff.

**Comment by Baroshem** [comment]
Hey @rhclayto 

I completely missed your response on this issue. My notifications for closed issues seems to be broken. As multistore is a functionality that can be used in some projects but does not have to work for all. I decided to only show in the docs how it works instead of imolementing it as for some users it may not be useful.

If you need any help implementing that, me or @michaelbromley can probably help 😉
