### ISSUE TITLE
[Feature]: implement multi currency support

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront-community/vendure#141]
### How the project can be improved?

For now we do not have a support for multiple currencies fetched from Vendure. It should be added an handled correcty.

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zmilan** [comment]
Hi @Baroshem,
I am interested in implementing this too

**Comment by Baroshem** [comment]
If I can, I would suggest to start working on the language support at first, and then when that task will be finished, focus on currency. These will be big features so better to review them one at the time :)

**Comment by Baroshem** [comment]
Done in #163
