### ISSUE TITLE
[Bug]: adding items overwrites previous cart content 

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront-community/vendure#146]
### Expected Behavior

Adding items to cart should update cart with new items.

### Actual Behavior

When adding new items to cart, it is overwritten instead of filling with the new products.

![vendure_cart](https://user-images.githubusercontent.com/32042425/143573513-ca54057a-0b85-4364-9768-9c0b154c078a.gif)

### What version of vendure integration are you using?

1.0.0-beta.3

### What version of Node.js are you using?

v16.13.0

### What browser (and version) are you using?

Chrome 96.0.4664.45

### What operating system (and version) are you using?

Ubuntu 20.04.3 LTS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelbromley** [comment]
This behaviour is typically seen when there is a problem with the session, i.e. the session token is not getting back to Vendure, so each time you add to cart, it actually creates a brand-new order.

You can verify whether this is the case by checking the admin ui order list, and see if there are lots of orders with single lines.

**Comment by AdamPawlinski** [comment]
Looks like you are right, there are a lot of orders with single lines. Thanks for explanation. So what should I do now?

**Comment by michaelbromley** [comment]
Did you set `tokenMethod: 'bearer'` as covered in the docs: https://docs.vuestorefront.io/vendure/guide/configuration.html ?

**Comment by AdamPawlinski** [comment]
Yes, I did.

**Comment by michaelbromley** [comment]
OK. Then the next step would be to try to find out what is happening to that bearer token:

1. Are the requests from the browser getting sent with the correct `Authorization: bearer <token>` headers?
2. Is VSF also correctly forwarding this header to Vendure when it makes API calls?

**Comment by Baroshem** [comment]
Cannot reproduce. Works on both listing and grid view.
