### ISSUE TITLE
[Bug]: Project is not building

### ISSUE THREAD

**Issue by rjdmacedo** [vuestorefront-community/vendure#176]
### Expected Behavior

As a software engineer I expect to build the project without any errors.

### Actual Behavior

When I run `yarn build` or `yarn dev` I get an error that will interrupt the build process.

### Possible Solution

In `packages/composables/src/getters/checkoutGetters.ts` remove one import (*1) and remove the typescript typing on `checkoutGetters` object (*2)

*1 - `import { CheckoutGetters } from '@vue-storefront/core';`
*2 - `export const checkoutGetters: CheckoutGetters<ShippingMethod> { ... }`

### Steps to reproduce

1. run `git pull` on `develop` branch
2. run `yarn install`
3. run `yarn dev` (or `yarn build`)

### What version of vendure integration are you using?

@vue-storefront/core@2.4.6

### What version of Node.js are you using?

v16.13.2

### What browser (and version) are you using?

CLI

### What operating system (and version) are you using?

macOS

### Relevant log output

```shell
[!] (plugin rpt2) Error: /.../.../.../vue-storefront-community/vendure/packages/composables/src/getters/checkoutGetters.ts(1,10): semantic error TS2305: Module '"@vue-storefront/core"' has no exported member 'CheckoutGetters'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rjdmacedo** [comment]
@Baroshem please add this issue to the correct Project & Milestone 🙏🏼

**Comment by Baroshem** [comment]
Thanks for reporting that! I have added it to 1.2.0

**Comment by justyna-13** [comment]
Hi @rjdmacedo I've tried to reproduce this error but I can't see it. It could be fixed in core so can you check it again?

**Comment by rjdmacedo** [comment]
@justyna-13 check your `yarn.lock` and see what version of `@vue-storefront/core` you are using.

Talked with @filipsobol about this issue and he told me that they had indeed removed that `CheckoutGetters` member.

Quoting 👇🏼 
> In the past we had `checkoutGetters` and `useCheckout` but it was impossible to enclose all checkout logic (especially because each integration is very different in how they deal with the checkout process) that we replaced them with more granular alternatives

**Comment by justyna-13** [comment]
It's "@vue-storefront/core@~2.4.1"
