### ISSUE TITLE
[Feature]: Get the default store language and currency from vendure  

### ISSUE THREAD

**Issue by KeetTechSol** [vuestorefront-community/vendure#180]
### How the project can be improved?

Since my customers are based only in the UK and they do not sell items to other countries, the default language is en_GB and the currency is GBP in vendure. It will be great if storefront can pick up these from the backend.

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hi @KeetTechSol 

Thanks for raising this issue. Indeed its quite useful feature. I will add it to our next major release roadmap :)

**Comment by Baroshem** [comment]
@KeetTechSol 

Could you take a look at this? https://github.com/vuestorefront-community/vendure/pull/163

Maybe it can solve your issue already?

**Comment by KeetTechSol** [comment]
@Baroshem
If I understand correctly, #163 gets currency for the current locale, which is selected in the storefront. The default locale is still hardcoded in the storefront. My suggestion is when vendure is connected, the storefront's default language and currency should align to that of vendure.
Hope I am not confusing you.

**Comment by Baroshem** [comment]
Closing as there is no further requirement for the feature.
