### ISSUE TITLE
[Feature]: SfBottomNavigation add active state to items

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront-community/vendure#189]
### How the project can be improved?

Needed to see which item is active currently. 
![Screenshot from 2022-03-18 12-09-28](https://user-images.githubusercontent.com/32042425/158992724-cd3e22ea-fbc7-44f0-9cf7-04a24c362aad.png)

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Closing as this feature was merged and released with 1.2.0. Thanks!
