### ISSUE TITLE
[Feature]: SfBottomNavigation add logic to basket item

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront-community/vendure#190]
### How the project can be improved?

Add logic to change the basket item label in BottomNavigation, when you are on `Home` it should be `basket` but when on product page `addToCart`.
![Screenshot from 2022-03-18 12-09-28](https://user-images.githubusercontent.com/32042425/158993267-ff1420c0-e90b-4ea3-82de-7df169cd182b.png)

![Screenshot from 2022-03-18 12-09-28](https://user-images.githubusercontent.com/32042425/158993459-4cc2fd76-d5dd-4dae-a4de-14ae1a5693c0.png)

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ymaheshwari1** [comment]
@AdamPawlinski Why are we thinking of changing the label to `Add to Cart` on product page?

**Comment by Baroshem** [comment]
This can be easily added on the frontend so no need to implement in the integration repo :)
