### ISSUE TITLE
[Bug]: MyReviews.vue page has null content

### ISSUE THREAD

**Issue by ekwoue** [vuestorefront-community/vendure#191]
### Actual Behavior

When I initiate a storefront project with vendure, the MyReviews.vue page has empty content.

Here is the generated project: https://github.com/ekwoue/storefront-vendure
The page that's empty: https://github.com/ekwoue/storefront-vendure/blob/master/pages/MyAccount/MyReviews.vue

I tried on another workstation under Windows 11 and Node 13.14.0 and I had the same problem.

Does MyReviews.vue page need to be generated?

### What version of vendure integration are you using?

1.5.0

### What version of Node.js are you using?

14.19.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hey @ekwoue 

Thanks for reporting that. This is kind of a strange issue TBH. I will investigate it in the upcoming days.

**Comment by Baroshem** [comment]
After second thought, Vendure does not have a reviews plugin implemented yet, so maybe this is the issue. We might have at some point removed this page as there is no support for reviews yet

**Comment by michaelbromley** [comment]
Yeah, Vendure has no built-in reviews support.

**Comment by Baroshem** [comment]
@ekwoue 

I know what is the problem. For some strange reason, the MyReviews.vue is a binary file in the template-vendure. I will remove it as Vendure does not have Reviews so we wont be able to cover it in VSF.

**Comment by Baroshem** [comment]
Will be released with a new 1.2.0 version -> https://github.com/vuestorefront-community/template-vendure/pull/11

**Comment by Baroshem** [comment]
Closing the issue as this bugfix was merged and released with 1.2.0
