### ISSUE TITLE
[Bug]: Cart IDs for anonymous users do not get persisted in any way

### ISSUE THREAD

**Issue by nentor** [vuestorefront-community/vendure#193]
### Expected Behavior

I expect that when I add something to the basket as an anonymous user to have the cart id persisted as a cookie.

### Actual Behavior

No ID gets persisted, which on refresh causes the basket to get lost. Upon adding a new item, an entirely new cart id is returned

### Steps to reproduce

I have cloned this repo and run everything from the current latest code on the "develop" branch. I have also run Vendure locally using an SQLite database. The way I've scaffolded Vendure is as their "Getting Started" documentation page recommends, through the CLI. 

It's worth noting that before I tried to run Vue Storefront from the development branch here, I also tried with a scaffolded version from the VSF CLI (v2.4.1).

### What version of vendure integration are you using?

1.0.0

### What version of Node.js are you using?

16.14.2

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS Monterey 12.3 on Vanilla M1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelbromley** [comment]
Hi, just to check - did you set the `authOptions.tokenMethod` to `'bearer'` in your Vendure config as instructed [here](https://docs.vuestorefront.io/vendure/guide/configuration.html#requirements)?

**Comment by nentor** [comment]
> Hi, just to check - did you set the `authOptions.tokenMethod` to `'bearer'` in your Vendure config as instructed [here](https://docs.vuestorefront.io/vendure/guide/configuration.html#requirements)?

Seems like I've missed reading this part... Added it and seems to be working like a charm now.

**Comment by Baroshem** [comment]
Resolved. Closing
