### ISSUE TITLE
[Bug]: email verification not working

### ISSUE THREAD

**Issue by macrozone** [vuestorefront-community/vendure#197]
### Expected Behavior

email verification link should work and verify the email

### Actual Behavior

the email gets sent out, but the link does not work:

Page not found
We are sorry that we can’t find the page, please go back or try again

the link is https://someurl.com/verify?token=sometoken

### Possible Solution

should be a minor thing to add this one route

### What version of vendure integration are you using?

1.1.0

### What version of Node.js are you using?

12.x

### What browser (and version) are you using?

chrome

### What operating system (and version) are you using?

macos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hey @macrozone 

Are you sure that this is a frontend issue? Seems more like Vendure to me. Also VSF by default does not support email verification.

Maybe @michaelbromley could help as well.

**Comment by macrozone** [comment]
@Baroshem it is definitly a frontend problem, because the verification email sends the user to a certain route on the frontend: https://someurl.com/verify?token=sometoken

the frontend should honor this route and call the corresponding api (depending on the shop-backend) and show some message or redirect the user somewhere.

**Comment by michaelbromley** [comment]
I think it's just not implemented in the VSF integration yet. 

Indeed, this is explicitly stated in the [docs](https://docs.vuestorefront.io/vendure/guide/configuration.html#requirements):
![image](https://user-images.githubusercontent.com/6275952/165520038-d4fa6acd-6242-4bde-8a24-98466d4edda8.png)

So I think this is more of a feature request on supporting the verification flow.

**Comment by Baroshem** [comment]
Closing this as it is out of the scope of VSF functionality.
