### ISSUE TITLE
[Feature]: expose getCode on order setters 

### ISSUE THREAD

**Issue by macrozone** [vuestorefront-community/vendure#203]
### How the project can be improved?

reason is described here: https://github.com/vuestorefront-community/vendure/pull/198#issue-1217873053

tldr; using an order's id as "public" reference for an order is not a good idea, as order list in vendure does not support searching for that, but only for the code. 

i propose to first add a getter, so that consumers of the vendure integration can optionally switch to using the code.

### What are the acceptance criteria?

- [x] orderGetters exposes `getCode()` that returns an orders `code`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Closing as this feature was merged and released with 1.2.0
