### ISSUE TITLE
Only featured asset is shown

### ISSUE THREAD

**Issue by OlegKunitsyn** [vuestorefront-community/vendure#206]
**Reproduction**
- go Vendure `/admin/catalog/products/1` (laptop)
- add 2nd asset i.e `22`
- two assets are in place, `/shop-api`:
```
{
  product(id: "1") {
    assets {
      id
    }
  }
}
{
  "data": {
    "product": {
      "assets": [
        {
          "id": "1"
        },
        {
          "id": "22"
        }
      ]
    }
  }
}
```
- only the first asset is shown `/p/1/laptop` in the storefront

**Comment by Baroshem** [comment]
Will be solved with #196
