### ISSUE TITLE
[Bug]: Shipping description missing and payment description wrong.

### ISSUE THREAD

**Issue by ablax** [vuestorefront-community/vendure#212]
### Expected Behavior

Shippings method description to be available.
Payment's and shipping's methods to be correct.

### Actual Behavior

Shipping method's description is missing.
Vendure passes us shipping's and payment method's descriptions as raw html and we render it as text which causes the description to be wrong - for example it starts with `<p>` and ends with `</p>.` You can style you descriptions as well.

### Possible Solution

Get the correct field for shipping description
Ue v-html instead of moustache

### What version of vendure integration are you using?

1.1.0

### What version of Node.js are you using?

14

### What browser (and version) are you using?

safari

### What operating system (and version) are you using?

macos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelbromley** [comment]
Ah yes, we'd have to use whatever mechanism Vue provides to safely set innerHTML of a div so this gets rendered correctly.
