### ISSUE TITLE
[Feature]: fetch products from Vendure

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront-community/vendure#220]
### How the project can be improved?

Currently there are ways to fetch single product (with custom fields) and multiple products (using search query but without custom fields)

The purpose of this task is to have a possibility to fetch multiple products with custom fields by using products query from Vendure.

As there is an ongoing architectural change to all VSF integrations that will probably be applied to this project as well I would recommend to follow it for this and future composables/functionality.

The main idea of the architectural change is to get rid of composables package and write composables as a part of the theme.

So this new useProducts composable should be a part of theme/composables and fetch data directly from the API-Client. So, the API-client part does not change at all.

Example of usePaymentProviderMock theme composable: 

```ts
// theme/composables/usePaymentProviderMock/index.ts

import { sharedRef } from '@vue-storefront/core';

// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
export const usePaymentProviderMock = () => {
  const status = sharedRef(false, 'usePaymentProviderMock-status');

  return {
    status
  };
};
```

The new useProducts composable should look something like this:

```ts
// packages/api-client/src/api/getProducts/index.ts

import gql from 'graphql-tag';
import productQuery from './productQuery';
import { CustomQuery } from '@vue-storefront/core';
import { Context, ProductParams, Product, GetProductsResponse, RequestDataStructure } from '../../types';
import { NO_CACHE_FETCH_POLICY } from '../../helpers/constants';

const getProducts = async (context: Context, params: ProductParams, customQuery?: CustomQuery): Promise<GetProductsResponse> => {
  const productVariables = {
    ...params
  };

  const { products } = context.extendQuery(
    customQuery, { products: { query: productsQuery, variables: productVariables } }
  );

  const request = await context.client.query<RequestDataStructure<'products', Product>>({
    query: gql`${products.query}`,
    variables: products.variables,
    fetchPolicy: NO_CACHE_FETCH_POLICY
  });
  return request;

};

export default getProduct;
```

Also the grapqhl query. You can replace the query I created with more appriopriate one.

```ts
// packages/api-client/src/api/getProducts/productsQuery.ts

import gql from 'graphql-tag';

export default gql`
  query products {
  products {
    items {
      id
      customFields
    }
  }
}
`;

```

Add aprioppriate types to vuestorefront-community/vendure/packages/api-client/src/types/API.ts

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qwexvf** [comment]
Thanks for the issue! i'm working on it atm!

**Comment by Baroshem** [comment]
Awesome @qwexvf 

I have assigned you! If you have any questions please let me know.

**Comment by Baroshem** [comment]
Closed the PR as this feature can be implemented as an extension instead of a whole new composable.
