### ISSUE TITLE
[Bug]: Password Can't Be Updated From My Account

### ISSUE THREAD

**Issue by skilltimate** [vuestorefront-community/vendure#222]
### Actual Behavior

I tried to update password from My Account section, it simply does not work.

### What version of vendure integration are you using?

Latest

### What version of Node.js are you using?

Latest

### What browser (and version) are you using?

Firefox

### What operating system (and version) are you using?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hey, could you provide more details? What are the reproduction steps, what error do you see?

**Comment by Baroshem** [comment]
Closing as there is no further contact and was not able to reproduce the error.
