### ISSUE TITLE
registerCustomerAccount custom query not executed

### ISSUE THREAD

**Issue by barakamwakisha** [vuestorefront-community/vendure#230]
### What is your question / Please describe your issue

I want to include the phoneNumber field when registering a customer. Following the guidance in [the docs](https://docs.vuestorefront.io/v2/composition/extending-graphql-queries.html), I registered a custom query in the `middleware.config.js` file.
```javascript
module.exports = {
  integrations: {
    vendure: {
      location: '@vue-storefront/vendure-api/server',
      configuration: {
        api: {
          uri: process.env.GRAPHQL_API,
          tokenMethod: process.env.TOKEN_METHOD,
          secret: process.env.SECRET
        },
      },
      customQueries: {
        'custom-register': ({ query, variables, metadata }) => {
          console.log('In custom query');
          variables.input.phoneNumber = metadata.phoneNumber;
          return { query, variables };
        }      
      }
    }
  }
}
```
In the component, I try to execute the custom query as show below.
```javascript
import { useUser } from '@vue-storefront/vendure';
const { register } = useUser();

register({
        user: form.value
        customQuery: {
          registerCustomerAccount: 'custom-register',
          metadata: { phoneNumber: phone.value.phoneNumber }
        }
})
```

However, the default register mutation is executed instead. The `In custom query` statement in the custom query function isn't even logged. What could I have done wrong? 

### What version of vendure are you using?

1.6.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by barakamwakisha** [comment]
Ended up using the `useVSFContext` composable.

```javascript
import { useVSFContext } from '@vue-storefront/core';
const { $vendure } = useVSFContext();
$vendure.api.registerCustomerAccount(form.value);
```

**Comment by Baroshem** [comment]
Hey @barakamwakisha

I am glad you found a workaround. If you have any other questions, please let me know 🙂
