### ISSUE TITLE
Build error Invalid 'main' field in

### ISSUE THREAD

**Issue by blackyzero** [vuestorefront-community/vendure#237]
### What is your question / Please describe your issue

Yarn build gives me following error

```
 ERROR  (node:3972) [DEP0128] DeprecationWarning: Invalid 'main' field in '/opt/services/vue/node_modules/@vue-storefront/nuxt-theme/package.json' of 'lib/module.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

```

### What version of vendure are you using?

1.7.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hey, this issue is caused by our core packages. It should not make your build fail.
