### ISSUE TITLE
Product image not show with matched attribute

### ISSUE THREAD

**Issue by blackyzero** [vuestorefront-community/vendure#239]
### What is your question / Please describe your issue

Hello,

The product image is not showing with matched attribute.
Ex: mango  with yellow color
mango with green color

For now, only one image showing, even with different selection.

Could you add this feature if it's not available ?
Thank you.

### What version of vendure are you using?

1.7.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blackyzero** [comment]
seems, price is also not being fetched when selecting different product attribute.

**Comment by Baroshem** [comment]
Hey, sorry no contact from my side. I was on long holidays.

From your description the functionality you mention is quite custom. At VSF, we are developing integartions in the generic way that works with the default (mocked/dummy data) project. Anything else should be implemented by the developers using the integration. The feature you mention can be useful to you, but unnecessary for other developers and we are aiming to deliver a functioning template.

In this case, I am affraid you have to find a way to develop an extension or custom query/code by yourself.

**Comment by Baroshem** [comment]
Closing as there was no response from the issue author. If the problem will occur, do not hesitate to reopen the issue and continue discussion :)

**Comment by blackyzero** [comment]
Sorry for my late reply.
and thanks for all.
